# Generated by Django 5.2.4 on 2025-07-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="share_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="share_now",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
