# Generated by Django 5.2.4 on 2025-07-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_share_at_post_share_now"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="share_complete_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
