# Generated by Django 5.2.4 on 2025-07-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_post_share_complete_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="share_start_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
